### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by matthias-t** [NerdyPepper/taizen#14]
With `cargo publish`, such that it can be installed with
```
cargo install taizen
```

**Comment by oppiliappan** [comment]
I will definitely put this to the bucketlist!

I am learning more about cargo and crates at the moment. This repo will be up on crates.io soon.

Thanks for opening the issue!

**Comment by oppiliappan** [comment]
We are up on crates.io now!

```cargo install taizen``` to quickly install the binary.

Sorry for the delay, I got to the chapter on Cargo and Crates only now :smile:

**Comment by matthias-t** [comment]
Thanks a lot, @NerdyPepper
