### ISSUE TITLE
Use the library Parse Wiki Text

### ISSUE THREAD

**Issue by ghost** [NerdyPepper/taizen#15]
Taizen currently parses wiki text in a naive way using regular expressions. Wiki text cannot be correctly parsed with regular expressions. I propose using Parse Wiki Text ([crates.io](https://crates.io/crates/parse_wiki_text), [Github](https://github.com/portstrom/parse_wiki_text)) to parse wiki text into a tree, and then formatting the output simply by walking the tree. See the readme of Parse Wiki Text for a description of the challenges of correctly parsing wiki text.

**Comment by oppiliappan** [comment]
Parse Wiki Text is a lifesaver!  
I will definitely get to work on this as soon as possible!

Thanks!

**Comment by ChristopherBilg** [comment]
After taking ownership of this issue, I see that `parse_wiki_text` was last released ~4 years ago. I don't think that bringing on more technical debt that is ~4 years old as a dependency is the best route forward at the moment. Currently looking into alternatives.
