### ISSUE TITLE
Cargo installation generates build erorr

### ISSUE THREAD

**Issue by rodrigolece** [NerdyPepper/taizen#21]
I tried installing using `cargo install taizen`. Before that I did a fresh installation of rust and others with `curl -sSf https://sh.rustup.rs | sh` and selecting the default options.

The install failed with the status

```
   Compiling taizen v0.1.0
error: linking with `cc` failed: exit code: 1
```
Then a bunch of options following `= note: "cc"` and finally

```
  = note: /usr/bin/ld: cannot find -lncursesw
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: failed to compile `taizen v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-installu9ladT`

Caused by:
  could not compile `taizen`.
```

I'm running Ubuntu 16.04.

**Comment by kusinara** [comment]
@rodrigolece 
The error is telling you that it can't find `ncursesw`, try
```
$ apt install libncursesw5-dev
```

**Comment by rodrigolece** [comment]
Thank you so much, that fixed it!

Can you give a piece of advice to a Linux beginner? How can I tell the name of the package that I should apt install, which is usually different from the name of the package that the error says is missing? Eg. how can I deduce that the `ncursesw` translates into `libncursesw5-dev`?

**Comment by kusinara** [comment]
@rodrigolece 
In this particular instance, it was a simple net search of the error.
If this wasn't the case, the Cursive library (the library used to create the TUI for taizen) [wiki](https://github.com/gyscos/Cursive/wiki/Install-ncurses) lists what version you need for each distribution.
