### ISSUE TITLE
Crate seems to be broken

### ISSUE THREAD

**Issue by ajstrand** [NerdyPepper/taizen#23]
I installed the app with cargo, but it appears to be broken.

I tried this example: `taizen https://pl.wikipedia.org/`, but there was no out put from the program. 

I also tried `taizen https://en.wikipedia.org/wiki/Railroads_in_New_England`, but that search returned nothing either.

**Comment by ChristopherBilg** [comment]
Working from the changes on the #25 branch, `taizen https://pl.wikipedia.org/` does indeed work.

Running a link to a direct page is not currently supported, but might be in the future.
